name: Docker Build & Push
b
# Bu işlem ne zaman çalışsın?
on:
    push:
        branches: ["main"] # sadece main branch'ine yapılan push işlemlerinde çalışsın
    pull_request:
        branches: ["main"] # main branch'ine açılan pull request'lerde çalışsın

jobs:
    build:
        runs-on: ubuntu-latest # İşlem için kullanılacak ortam ubuntu seçtik

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3 # Kodumuzu repodan çekiyoruz

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2 # Docker Buildx kurulumu

            - name: Login to DockerHub
              uses: docker/login-action@v2 # DockerHub'a giriş yapıyoruz
              with:
                  username: ${{ secrets.DOCKER_USERNAME }} # DockerHub kullanıcı adı
                  password: ${{ secrets.DOCKER_PASSWORD }}    # DockerHub erişim token'ı

            - name: Build and Push
              uses: docker/build-push-action@v4 # Docker imajını build ve push işlemi
              with:
                    context: . # Dockerfile'ın bulunduğu dizin
                    push: true # İmajı DockerHub'a push et
                    tags: guvenchemy/shortlink-app:latest # İmaj etiketi  